name: Automatisierte Datenextraktion und Modelltraining

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.1' 

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Scrape URLs
      run: python Backend/scrape_URL.py
      working-directory: ${{ github.workspace }}

    - name: Scrape Nutrition Data
      run: python Backend/scraper_Nutrition.py
      working-directory: ${{ github.workspace }}
      
    - name: Train Model
      run: python train_model.py
